apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lhci-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lhci-server
spec:
  selector:
    matchLabels:
      name: lhci-server
  # there can be only one pod at a time because of the persistent volume claim
  strategy:
    type: Recreate
  template:
    metadata:
      name: lhci-pod
      labels:
        name: lhci-server
    spec:
      containers:
        - name: lhci-server
          image: lighthouse
          volumeMounts:
            - mountPath: '/data'
              name: lhci-data-volume
          # required for ingress health checks to work
          ports:
            - containerPort: 9001
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9001
      volumes:
        - name: lhci-data-volume
          persistentVolumeClaim:
            claimName: lhci-data-claim
---
apiVersion: v1
kind: Service
metadata:
  name: lhci-server
spec:
  ports:
  - port: 9001
    targetPort: 9001
    nodePort: 32222
  selector:
    name: lhci-server
  type: NodePort
