---
apiVersion: v1
kind: Namespace
metadata:
  name: lighthouse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lighthouse
  name: deployment-lighthouse
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-lhci
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-lhci
    spec:
      containers:
      - name: app-lhci-bk
        image: lighthouse
        ports:
          - name: app-lhci-bk
            containerPort: 9001
        volumeMounts:
        - mountPath: /data
          name: cache-volume
      - name: app-lhci-fr
        image: lighthouse-nginx
        ports:
        - containerPort: 80
      volumes:
        - name: cache-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: lighthouse
  name: service-lighthouse
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-lhci
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: lighthouse
  name: ingress-lighthouse
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /healthcheck
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: service-lighthouse
              servicePort: 80
