apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: lighthouse
build:
  artifacts:
  - image: lighthouse
    docker:
      dockerfile: Dockerfile-lh
  - image: lighthouse-nginx
    docker:
      dockerfile: Dockerfile-ng
deploy:
  kubectl:
    manifests:
    - k8s-manifest.yml
