awsRegion: <region>

rbac:
  create: true
  serviceAccount:
    # This value should match local.k8s_service_account_name in locals.tf
    name: kube-system
    annotations:
      # This value should match the ARN of the role created by module.iam_assumable_role_admin in irsa.tf
      eks.amazonaws.com/role-arn: "role arn"

autoDiscovery:
  clusterName: <cluster-name>
  enabled: true
